// <auto-generated/> hand-written replacement for EventExtensionGenerator

using Lagrange.Core;
using Lagrange.Core.Events.EventArgs;
using Lagrange.Milky.Events;

namespace Lagrange.Milky.Events.Extensions;

public static partial class EventExtension
{
    public static partial void RegisterConvertibleEvents(this BotContext lagrange, IGenericEventHandler handler)
    {
        lagrange.EventInvoker.RegisterEvent<BotGroupInviteNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotOfflineEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotFriendRequestEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupInviteNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupJoinNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupMemberDecreaseEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupMemberIncreaseEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupReactionEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotGroupNudgeEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotFriendRecallEvent>(handler.OnEvent);
        lagrange.EventInvoker.RegisterEvent<BotMessageEvent>(handler.OnEvent);
    }

    public static partial void UnregisterConvertibleEvents(this BotContext lagrange, IGenericEventHandler handler)
    {
        lagrange.EventInvoker.UnregisterEvent<BotGroupInviteNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotOfflineEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotFriendRequestEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupInviteNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupJoinNotificationEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupMemberDecreaseEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupMemberIncreaseEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupReactionEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotGroupNudgeEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotFriendRecallEvent>(handler.OnEvent);
        lagrange.EventInvoker.UnregisterEvent<BotMessageEvent>(handler.OnEvent);
    }

    public static partial Microsoft.Extensions.DependencyInjection.IServiceCollection AddEventConverters(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupInviteNotificationEvent>), typeof(Lagrange.Milky.Events.Converters.GroupInvitationEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotOfflineEvent>), typeof(Lagrange.Milky.Events.Converters.BotOfflineEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotFriendRequestEvent>), typeof(Lagrange.Milky.Events.Converters.FriendRequestEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupInviteNotificationEvent>), typeof(Lagrange.Milky.Events.Converters.GroupInvitedJoinRequestEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupJoinNotificationEvent>), typeof(Lagrange.Milky.Events.Converters.GroupJoinRequestEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupMemberDecreaseEvent>), typeof(Lagrange.Milky.Events.Converters.GroupMemberDecreaseEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupMemberIncreaseEvent>), typeof(Lagrange.Milky.Events.Converters.GroupMemberIncreaseEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupReactionEvent>), typeof(Lagrange.Milky.Events.Converters.GroupMessageReactionEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotGroupNudgeEvent>), typeof(Lagrange.Milky.Events.Converters.GroupNudgeEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotFriendRecallEvent>), typeof(Lagrange.Milky.Events.Converters.MessageRecallEventConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(Lagrange.Milky.Events.Converters.IEventConverter<BotMessageEvent>), typeof(Lagrange.Milky.Events.Converters.MessageReceiveConverter), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));
        return services;
}
}