name: Build CharonAnchor 3.2.29

on:
  push:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-milky.yaml
    with:
      version: "3.2.29"
      deb_url: "https://qqdl.gtimg.cn/qqfile/QQNT/9.9.31/release/00e6a3e7/QQ_3.2.29_260528_amd64_01.deb"
