name: Build CharonAnchor

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang zlib1g-dev

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish
        run: dotnet publish Lagrange.Milky -c Release -r linux-x64 -p:DebugType=none -p:StripSymbols=true -p:OptimizationPreference=Size

      - uses: actions/upload-artifact@v4
        with:
          name: CharonAnchor-linux-x64
          path: Lagrange.Milky/bin/Release/net10.0/linux-x64/publish/Lagrange.Milky
